# Generated by Django 3.2.8 on 2021-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('Name_1', models.CharField(max_length=100)),
                ('Name_2', models.CharField(max_length=100)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
            ],
        ),
    ]
