# Generated by Django 3.2.8 on 2021-12-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='id',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='Question',
            field=models.TextField(max_length=200),
        ),
    ]
