# Generated by Django 3.2.8 on 2021-12-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20211210_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2021-12-11'),
            preserve_default=False,
        ),
    ]
