# Generated by Django 3.2.8 on 2021-12-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20211210_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
