# Generated by Django 3.2.8 on 2021-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_poll_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='count_2',
            field=models.IntegerField(default=10),
        ),
    ]
